title: PIXEL.RIP
description: PIXEL.RIP is simply trying to learn how to make video games.
author: PIXEL.RIP

url: "https://pixel.rip" 
baseurl: ""

rss_description: Subscribe to all posts
rss_limit: 20
timezone: America/Chicago

permalink: /:categories/:title/

markdown: kramdown
highlighter: rouge